typography_spectrum: 0.2286027972586453
color:
  brandStrength: 0.3726615842897445
  lightness: 0.09261517319828272
  saturation: 0.7813356302212924
  rhythmicContrast: 0.33855113643221557
  brandColors:
    - '#FDFDFD'
    - '#00584A'
    - '#F3AE0D'
    - '#60948A'
    - '#98BFBB'
layout_spectrum: 0.3341784898657352
name: Renew Australia
navigation:
  - name: Why?
    url: >-
      http://www.abc.net.au/news/2016-04-08/wa-treasurer-slams-gst-carve-up/7309644
    type: external
  - name: How it was done
    url: >-
      https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwig9pzYvrjOAhUKmpQKHTK5CwoQFggkMAE&url=http%3A%2F%2Fwww.aph.gov.au%2Fabout_parliament%2Fparliamentary_departments%2Fparliamentary_library%2Fflagpost%2F2014%2Fjuly%2Fgst-relativities-where-is-revenue-raised&usg=AFQjCNFEmFI8ZqgKCH3vLyuL9PIISxrZdg
    type: external
  - name: Where we are headed
    url: >-
      https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=6&cad=rja&uact=8&ved=0ahUKEwig9pzYvrjOAhUKmpQKHTK5CwoQFgg-MAU&url=http%3A%2F%2Fwww.abc.net.au%2Fnews%2F2016-05-18%2Fopposition-says-wa-budget-shows-government-in-crisis%2F7426132&usg=AFQjCNGG05WcbnTYZrGeK8kp6KOsc2TDSQ
    type: external
title: Direct Democracy Politics
description: people for the people
